---
title: "RobustPlotting"
output: html_document
date: "2025-01-30"
---

```{r echo=TRUE, results='hide', error=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r include=FALSE}
data.path.atp = "//wsl.localhost/Ubuntu-24.04/home/rsethi/school_rsh/PKH/systems_modelling_toolkit/data/pi3k_pten_totals/current_fit_atp.csv"
data.path.lps = "//wsl.localhost/Ubuntu-24.04/home/rsethi/school_rsh/PKH/systems_modelling_toolkit/data/pi3k_pten_totals/current_fit_lps.csv"
data.path.atp.ca = "//wsl.localhost/Ubuntu-24.04/home/rsethi/school_rsh/PKH/systems_modelling_toolkit/data/pi3k_pten_totals/current_fit_atp_ca.csv"
data.path.ly294 = "//wsl.localhost/Ubuntu-24.04/home/rsethi/school_rsh/PKH/systems_modelling_toolkit/data/pi3k_pten_totals/current_fit_ly294.csv"
```

```{r}
df.lps = read.csv(data.path.lps)
df.ly294 = read.csv(data.path.ly294)
df.atp = read.csv(data.path.atp)
df.atp.ca = read.csv(data.path.atp.ca)
colnames(df.lps)[1] = "TIME"
colnames(df.ly294)[1] = "TIME"
colnames(df.atp)[1] = "TIME"
colnames(df.atp.ca)[1] = "TIME"
```

```{r}
head(df.atp)
```

```{r}
df = data.frame(TIME=df.atp$TIME, LPS=df.lps$pAKT, ATP=df.atp$pAKT, LY=df.ly294$pAKT, ATP_Ca=df.atp.ca$pAKT)
df %>%
  pivot_longer(cols = c(-TIME), names_to="STIMULI", values_to="VALUES") %>%
  ggplot(aes(x=TIME, y=VALUES, color=STIMULI)) +
  geom_line()
```


```{r}
df.raw %>%
  pivot_longer(cols = c(-TIME), names_to="SUBSTRATE", values_to="CONCENTRATIONS") %>%
  ggplot(aes(x=TIME, y=CONCENTRATIONS, color=SUBSTRATE)) +
  geom_line()
```

```{r}
df.li %>%
  pivot_longer(cols = c(pAKT), names_to="SUBSTRATE", values_to="CONCENTRATIONS") %>%
  ggplot(aes(x=TIME, y=CONCENTRATIONS, color=SUBSTRATE)) +
  geom_line()
```

```{r}
df.li %>%
  pivot_longer(cols = c(-TIME), names_to="SUBSTRATE", values_to="CONCENTRATIONS") %>%
  ggplot(aes(x=TIME, y=CONCENTRATIONS, color=SUBSTRATE)) +
  geom_line()
```

